# Generated by Django 4.2.14 on 2024-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-0", "Player 1 Wins"),
                            ("0-1", "Player 2 Wins"),
                            ("1/2-1/2", "Draw"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("round", models.IntegerField()),
            ],
        ),
    ]
