# Generated by Django 4.2.14 on 2024-07-18 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                related_name="tournaments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
